### ISSUE TITLE
redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 11443 192.168.10.2:6379

### ISSUE THREAD

**Issue by hiake21c** [ran-jit/tomcat-cluster-redis-session-manager#39] opened 2019-05-19 19:46 UTC
I using redis cluste. and when I do "session.invalidate();"

 "JedisMovedDataException" error occured 

I using this version : tomcat-cluster-redis-session-manager-3.0.1
and my tomcat version is "8.0.24"

here is ERROR message

redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 11443 192.168.10.3:6379
	at redis.clients.jedis.Protocol.processError(Protocol.java:115)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
	at redis.clients.jedis.BinaryJedis.setnx(BinaryJedis.java:599)
	at tomcat.request.session.data.cache.impl.redis.RedisManager.setnx(RedisManager.java:52)
	at tomcat.request.session.data.cache.impl.redis.RedisCache.setnx(RedisCache.java:36)
	at tomcat.request.session.redis.SessionManager.createSession(SessionManager.java:100)
	at tomcat.request.session.redis.SessionManager.createSession(SessionManager.java:28)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2889)
	at org.apache.catalina.connector.Request.getSession(Request.java:2254)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:895)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:231)
	at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:568)
	at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:513)
	at blackweb.modules.accounts.SessionLoginModule.getLoginUser(SessionLoginModule.java:20)
	at blackweb.modules.accounts.CookieLoginActionFilter.preDoAction(CookieLoginActionFilter.java:38)
	at huck.pasta2.ActionProcessor$ActionFilterProcessor.preDoAction(ActionProcessor.java:27)
	at huck.pasta2.ActionProcessor.process(ActionProcessor.java:110)
	at huck.pasta2.DirectoryProcessor.process(DirectoryProcessor.java:79)
	at huck.pasta2.Pasta2Servlet.service(Pasta2Servlet.java:86)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:468)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:439)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:305)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:399)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:180)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hiake21c** [comment] 2019-05-19 19:48
here is my redisconfig

#-- Redis data-cache configuration

#- redis hosts ex: 127.0.0.1:6379, 127.0.0.2:6379, 127.0.0.2:6380, ....
redis.hosts=192.168.10.3:6379, 192.168.10.4:6379, 192.168.10.5:6379, 192.168.10.6:6379, 192.168.10.7:6379, 192.168.10.8:6379

#- redis password
#redis.password=

#- set true to enable redis cluster mode (default value: false)
redis.cluster.enabled=enabled

#- set true to enable redis sentinel mode (default value: false)
redis.sentinel.enabled=false
# redis sentinel master name (default value: mymaster)
redis.sentinel.master=mymaster

#- redis database (default value: 0)
#redis.database=0

#- redis connection timeout (default value: 2000 ms)
#redis.timeout=2000

#- enable redis and standard session mode. (default value: false)
# If enabled,
#   1. Must be enabled sticky session in your load balancer configuration. Else this manager may not return the updated session values.
#   2. Session values are stored in local jvm and redis.
#   3. If redis is down/not responding, requests uses jvm stored session values to process user requests. Redis comes back the values will be synced.
lb.sticky-session.enabled=false

**Comment by ran-jit** [comment] 2019-05-19 20:44
Hi @hiake21c,

The issue is due to Jedis 2.9.0. So I upgraded Jedis to the latest version 3.0.1.

I do not have a cluster environment ready to test. So I request you to kindly update your session manager to [3.0.2 pre-release](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.2) and check the same.

Please let me if the issue persists.

I hope it solves the issue!

Thanks!

**Comment by hiake21c** [comment] 2019-05-19 21:03
I think this is was configuration problem.

I changed configuration 

redis.cluster.enabled=enabled => redis.cluster.enabled=true

and then now it is works. I tested 3.0.1 version.

**Comment by ran-jit** [comment] 2019-05-19 21:13
Thanks, @hiake21c for the update. I'm currently on vacation. So I will test the latest changes in some time and update the release.

I'm closing this. If you require additional details in the future, please feel free to reopen this/create a new issue.

Thanks!

**Closed by ran-jit** 2019-05-19 21:13 UTC
